version: "2"

networks:
  sfira-network:
    driver: bridge

services:
  database:
    image: sfira-database
    build:
      context: .
      dockerfile: .docker/database.Dockerfile
    restart: always
    environment:
    # must be same as in "appsettings.json"
      - POSTGRES_USER=sfira
      - POSTGRES_PASSWORD=sfira
      - POSTGRES_DB=sfiradb
    networks:
      sfira-network:
        aliases:
          - database
    # ports:
    #   - "5433:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data


  application:
    image: sfira-application
    build:
      context: .
      dockerfile: .docker/application.Dockerfile
    restart: always
    networks:
      sfira-network:
        aliases:
          - application
    depends_on:
      - "database"
    ports:
      - "8000:80"
    volumes:
      - userfiles:/app/wwwroot/media/user

volumes:
  userfiles:
  postgresdata:
