version: "2"

networks:
  network:
    driver: bridge

services:
  database:
    image: sfira-database
    build:
      context: .
      dockerfile: .docker/database.Dockerfile
    restart: always
    environment:
      - POSTGRES_USER=${Database_User}
      - POSTGRES_PASSWORD=${Database_Password}
      - POSTGRES_DB=${Database_Name}
    networks:
      network:
        aliases:
          - database
    ports:
      - ${Database_Port}:5432
    volumes:
      - postgresdata:/var/lib/postgresql/data

  application:
    image: sfira-application
    build:
      context: .
      dockerfile: .docker/application.Dockerfile
    restart: always
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__PostgreSQL=Host=database; Port=5432; Database=${Database_Name}; Username=${Database_User}; Password=${Database_Password}; Pooling=true
    networks:
      network:
        aliases:
          - application
    volumes:
      - userfiles:/app/wwwroot/media/user
    depends_on:
      - database

  proxy:
    image: sfira-proxy
    build:
      context: .
      dockerfile: .docker/proxy.Dockerfile
    restart: always
    networks:
      network:
        aliases:
          - proxy
    ports:
      - ${Application_Port}:80
    depends_on:
      - application

volumes:
  userfiles:
  postgresdata:
