version: "2"

networks:
  network:
    driver: bridge

services:
  database:
    image: sfira-database
    build:
      context: .
      dockerfile: .docker/database.Dockerfile
    restart: always
    environment:
      - POSTGRES_USER=${Database_Username}
      - POSTGRES_PASSWORD=${Database_Password}
      - POSTGRES_DB=${Database_Name}
    networks:
      network:
        aliases:
          - database
    ports:
      - ${Database_Port}:5432
    volumes:
      - postgresdata:/var/lib/postgresql/data

  application:
    image: sfira-application
    build:
      context: .
      dockerfile: .docker/application.Dockerfile
    restart: always
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__PostgreSQL=Host=database; Port=5432; Database=${Database_Name}; Username=${Database_Username}; Password=${Database_Password}; Pooling=true
      - Seeding__SeedDummyData=${Database_SeedDummyData}
      - EmailSender__Host=${EmailSender_Host}
      - EmailSender__Port=${EmailSender_Port}
      - EmailSender__Username=${EmailSender_Username}
      - EmailSender__Password=${EmailSender_Password}
      - EmailSender__SenderName=${EmailSender_SenderName}
      - FileUploader__ImageQuality=${FileUploader_ImageQuality}
      - CachedStorage__Cached__MaxCount=${CachedStorage_Cached_MaxCount}
      - JobScheduler__PopularContent__IntervalInMinutes=${JobScheduler_PopularContent_IntervalInMinutes}
      - JobScheduler__PopularContent__PeriodInMinutes=${JobScheduler_PopularContent_PeriodInMinutes}
      - JobScheduler__PopularContent__SamplesPerMinute=${JobScheduler_PopularContent_SamplesPerMinuteOfPeriod}
      - JobScheduler__PopularContent__PopularUsersCount=${JobScheduler_PopularContent_PopularUsersCount}
      - JobScheduler__PopularContent__TrendingTagsCount=${JobScheduler_PopularContent_TrendingTagsCount}
      - Feed__PostsFeedCount=${PostsFeed_Count}
    networks:
      network:
        aliases:
          - application
    volumes:
      - userfiles:/app/wwwroot/media/user
    depends_on:
      - database

  proxy:
    image: sfira-proxy
    build:
      context: .
      dockerfile: .docker/proxy.Dockerfile
    restart: always
    networks:
      network:
        aliases:
          - proxy
    ports:
      - ${Application_Port}:80
    depends_on:
      - application

volumes:
  userfiles:
  postgresdata:
